server:
  port: 1299

spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      service:
        git:
          uri: https://github.com/BELOST-LGH/hrm-config.git #创库地址

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true #以ip注册
